models/topic.py
from models import Model


class Topic(Model):
    __fields__ = Model.__fields__ + [
        ('content', str, ''),
        ('title', str, ''),
        ('user_id', str, ''),
        ('board_id', str, ''),
        ('views', int, 0)
    ]

    @classmethod
    def get(cls, id):
        m = cls.find(id)
        new = m.views + 1
        m.update(views=new)
        return m

    def replies(self):
        from .reply import Reply
        rs = Reply.find_all(topic_id=self._id)
        return rs

    def board(self):
        from .board import Board
        b = Board.find(self.board_id)
        return b

    def user(self):
        from .user import User
        u = User.find(id=self.user_id)
        return u


from pymongo import MongoClient
from bson import ObjectId
import time
client = MongoClient()
# 创建数据库 bbs
db = client["bbs"]
t = Topic.find('5c445b499252f94720da9933')
# print(type(t))
# for i in t:
t.update(views=10)
print(t._id)
# t.update(views=10)
t = Topic.find('5c445b499252f94720da9933')

print(t.__dict__)
# t.update(views=10)

routes/reply.py
from flask import (
    request,
    redirect,
    url_for,
    Blueprint,
)

from routes import current_user

from models.reply import Reply


main = Blueprint('reply', __name__)


@main.route("/add", methods=["POST"])
def add():
    form = request.form
    u = current_user()
    m = Reply.new(form, user_id=u._id)
    m.save()
    return redirect(url_for('topic.detail', id=m.topic_id))

routes/topic.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
    abort,
    flash)
from routes import current_user

from models.board import Board
from models.topic import Topic
import uuid

from utils import log

main = Blueprint('topic', __name__)


csrf_tokens = dict()


@main.route("/")
def index():
    board_id = request.args.get("board_id", -1)
    if board_id == -1:
        ts = Topic.all()
    else:
        ts = Topic.find_all(board_id=board_id)
    bs = Board.all()
    u = current_user()
    # log("u: ", u)
    # log("type of u: ", type(u))
    if u is not None:
        token = str(uuid.uuid4())
        csrf_tokens[token] = u._id
        return render_template("topic/index.html", ts=ts, token=token, bs=bs)
    else:
        return render_template("topic/index.html", ts=ts, bs=bs)


@main.route('/<id>/')
def detail(id):
    topic = Topic.get(id)
    board = topic.board()
    user = topic.user()
    return render_template("topic/detail.html",
                           topic=topic, board=board, user=user)


@main.route("/add", methods=["POST"])
def add():
    form = request.form
    u = current_user()
    log("form: ", form)
    m = Topic.new(form, user_id=u._id)
    m.save()
    log("m: ", m)
    # log("m_id :", m.id)
    # log("m_id type :", type(m.id))
    return redirect(url_for('.detail', id=str(m.id)))


@main.route("/delete")
def delete():
    id = request.args.get("id")
    u = current_user()
    token = request.args.get("token")
    # 判断token是否是我们给的
    if token in csrf_tokens and csrf_tokens[token] == u._id:
        csrf_tokens.pop(token)
        if u is not None:
            Topic.delete(id)
            return redirect(url_for('.index'))
        else:
            abort(404)
    else:
        flash("对不起你没有权限")
        return redirect(url_for('.index'))


@main.route("/new")
def new():
    bs = Board.all()
    return render_template("topic/new.html", bs=bs)

templates/topic/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>bbs club</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet" href="/static/lib/editor/editor.css">
    <link rel="stylesheet" href="/static/lib/webuploader/webuploader.css">
    <script src="/static/lib/jquery-3.0.0.min.js"></script>
    <script src="/static/lib/markdownit.js"></script>
    <script src="/static/lib/webuploader/webuploader.withoutimage.js"></script>
    <script src="/static/lib/editor/editor.js"></script>
    <script src="/static/lib/editor/ext.js"></script>
</head>
<body>
<div id="main">
    <div id="content">
        <div class='panel'>
            <div class='header topic_header'>
      <span class="topic_full_title">
        {{ topic.title }}
      </span>
                <div class="changes">
        <span>
          发布于 7 天前
        </span>
                    <span>
          作者 {{ user.username }}
        </span>
                    <span>
          {{ topic.views }} 次浏览
        </span>


                    <span> 来自 {{ board.title }}</span>


                </div>
            </div>
            <div class="inner topic">
                <div class="topic_content">
                    <div class="markdown-text">
                        {{ topic.content }}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="panel">
        <div class="header">
            <span class="col_fade">{{ topic.replies() | length }} 回复</span>
        </div>
        {% for r in topic.replies() %}
        <div class="cell reply_area reply_item">
            <div class="author_content">
                <a href="" class="user_avatar">
                    <img src="https://avatars0.githubusercontent.com/u/6939365?v=4&amp;s=120" title="{{ r.user().username }}">
                </a>
                <div class="user_info">
                    <a class="dark reply_author">{{ r.user().username }}</a>
                    <a class="reply_time">{{ loop.index }}楼 • 4 个月前</a>

                </div>
                <div class="user_action">
      <span>
        <i class="fa up_btn
          fa-thumbs-o-up
          invisible" title="喜欢"></i>
        <span class="up-count">
        </span>
      </span>
                </div>
            </div>
            <div class="reply_content from-yinxin630">
                <div class="markdown-text">
                    <p>{{ r.content }}</p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <div id="reply">
        <form method="post" action="{{ url_for('reply.add') }}">
            <input type="hidden" name="topic_id" value="{{ topic._id }}">
            <textarea name="content"></textarea>
            <button>添加回复</button>
        </form>
    </div>
</div>
</body>
</html>

templates/topic/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>bbs club</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet" href="/static/lib/editor/editor.css">
    <link rel="stylesheet" href="/static/lib/webuploader/webuploader.css">
    <script src="/static/lib/jquery-3.0.0.min.js"></script>
    <script src="/static/lib/markdownit.js"></script>
    <script src="/static/lib/webuploader/webuploader.withoutimage.js"></script>
    <script src="/static/lib/editor/editor.js"></script>
    <script src="/static/lib/editor/ext.js"></script>
</head>
<body>
<div id="main">
    <div id="sidebar">
        <div class="panel">
            <div class="inner">
                <a href="/topic/new" class="create_topic_btn">
                    <span class="span-success">发布话题</span>
                </a>
            </div>
        </div>
    </div>
    <div id="content">
        <div class="panel">
            {% for msg in get_flashed_messages() %}
            <p>{{ msg }}</p>
            {% endfor %}
            <div class="header">
                <a href="/topic" class="topic-tab current-tab">
                    全部
                </a>
                {% for b in bs %}
                <a href="/topic?board_id={{ b['_id'] }}" class="topic-tab current-tab">
                    {{ b.title }}
                </a>
                {% endfor %}
            </div>
            <div class="inner post">
                <div class="topic_list">
                    {% for t in ts %}
                    <div class="cell">
                        <div class="topic_title_wrapper">
                            <a class="user_avatar pull-left">
                                <img src="{{ '/uploads/' + t.user().user_image + '?v=3&amp;s=120' }}"
                                     title="{{ t.user().username }}">
                            </a>

                            <a class="topic_title" href="{{ url_for('topic.detail', id=t._id) }}">
                                {{ t.title }}
                            </a>
                            <span>
                                    {{ t.replies() | length }} / {{ t.views }}
                                </span>
                            <a class="topic_delete" href="{{ url_for('topic.delete', token=token, id=t._id) }}">
                                删除
                            </a>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>
<script>
  (function () {
    var editor = new Editor();
    editor.render($('.editor')[0]);
  })();



</script>
</body>
</html>

templates/topic/new.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>bbs club</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet" href="/static/lib/editor/editor.css">
    <link rel="stylesheet" href="/static/lib/webuploader/webuploader.css">
    <script src="/static/lib/jquery-3.0.0.min.js"></script>
    <script src="/static/lib/markdownit.js"></script>
    <script src="/static/lib/webuploader/webuploader.withoutimage.js"></script>
    <script src="/static/lib/editor/editor.js"></script>
    <script src="/static/lib/editor/ext.js"></script>
</head>
<body>
<div id="main">
    <div id="content">
        <div class="panel">
            <div class="inner post">
                <form id="create_topic_form" method="post" action="{{ url_for('.add') }}">
                    <fieldset>
        <textarea autofocus class='span9' id='title'
                  name='title' rows='1'
                  placeholder="标题字数 10 字以上"></textarea>
                        <select name="board_id" id="board" required>
                            <option value="">请选择</option>
                                {% for b in bs %}                   
                                <option value="{{ b._id }}">{{ b.title }}</option>
                                {% endfor %}                     
                        </select>

                        <div class='markdown_editor in_editor'>
                            <div class='markdown_in_editor'>
                                <textarea class='editor' name='content' rows='20'
                                          placeholder='文章支持 Markdown 语法, 请注意标记代码'></textarea>
                                <div class='editor_buttons'>
                                    <input type="submit" class='span-primary submit_btn' data-loading-text="提交中"
                                           value="提交">
                                </div>
                            </div>
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
</div>
<script>
  (function () {
    var editor = new Editor();
    editor.render($('.editor')[0]);
  })();

</script>
</body>
</html>